services:
  frontend:
    build:
      context: ../kvault-frontend
    image: kvault-frontend
    ports:
      - "${FRONTEND_PORT:-80}:80"
    environment:
      - API_PORT=${API_PORT:-6767}
    depends_on:
      - api
    restart: unless-stopped
    container_name: kvault_frontend

  api:
    build:
      context: .
    image: kvault
    env_file: .env
    depends_on:
      pg:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    restart: unless-stopped
    container_name: kvault_api

  worker:
    image: kvault
    pull_policy: never
    command: ["./worker"]
    env_file: .env
    depends_on:
      pg:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_started
    restart: unless-stopped
    container_name: kvault_worker

  migrate:
    image: kvault
    pull_policy: never
    command: ["./migrate", "up"]
    env_file: .env
    depends_on:
      pg:
        condition: service_healthy
    restart: "no"
    container_name: kvault_migrate

  redis:
    image: redis:7
    restart: unless-stopped
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/redis/entrypoint.sh:/entrypoint.sh
    environment:
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    container_name: kvault_redis

  pg:
    image: postgres:18-alpine
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/18/docker
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h 127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: kvault_pg

  garage:
    image: dxflrs/garage:v2.2.0
    restart: unless-stopped
    ports:
      - "${GARAGE_S3_PORT:-3900}:3900"
    volumes:
      - "./docker/garage/garage.toml:/etc/garage.toml"
      - garage_meta:/var/lib/garage/meta
      - garage_data:/var/lib/garage/data
    container_name: kvault_garage

volumes:
  pg_data:
  garage_meta:
  garage_data:
