DROP TABLE IF EXISTS item_tags CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS file_meta CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TYPE IF EXISTS file_status;
DROP TYPE IF EXISTS item_type;