DROP TABLE IF EXISTS item_tags CASCADE;
DROP TABLE IF EXISTS tags CASCADE;

DROP INDEX IF EXISTS files_fts;
DROP TABLE IF EXISTS files CASCADE;
DROP TYPE IF EXISTS file_status;

DROP INDEX IF EXISTS items_fts;
DROP TABLE IF EXISTS items CASCADE;
DROP TYPE IF EXISTS item_type;

DROP TABLE IF EXISTS users CASCADE;