name: Mirror to GitVerse

on:
  push:
    branches:
      - "**"
  tags:
    - "**"

jobs:
  gitverse-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to GitVerse
        env:
          GITVERSE_URL: "https://x-token-auth:${{ secrets.GITVERSE_TOKEN }}@gitverse.ru/qvarkk/kvault.git"
        run: |
          git push --prune --force "$GITVERSE_URL" "+refs/remotes/origin/*:refs/heads/*" "+refs/tags/*:refs/tags/*"
